name: Sync to Hugging Face
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update hf.Dockerfile version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          sed -i "s|hoopstreet/tiktok-prompt-generator:v.*|hoopstreet/tiktok-prompt-generator:$VERSION|g" hf.Dockerfile
      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"
          git remote add hf https://hoopstreet:$HF_TOKEN@huggingface.co/spaces/hoopstreet/TikTok-Prompt-Generator
          git push hf main --force
